version: 1

loggers:
  revscoring:
    level: ERROR
    handlers: [stdout]
  ores:
    level: WARNING
    handlers: [stdout]
  celery:
    level: WARNING
    handlers: [stdout]

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: basic_human
    stream: ext://sys.stdout

formatters:
  basic_human: 
    format: "%(asctime)s %(levelname)s:%(name)s -- %(message)s"

