logging:
  version: 1
  root:
    handlers:
      - file
      - logstash
  loggers:
    revscoring:
      level: ERROR
    ores:
      level: ERROR
    ores.metrics_collectors.logger:
      level: ERROR
    celery:
      level: ERROR
    requests:
      level: ERROR
    revscoring.dependencies.dependent:
      level: ERROR
    stopit:
      level: ERROR
  handlers:
    file:
      class: logging.handlers.TimedRotatingFileHandler
      filename: /srv/log/ores/app.log
      formatter: basic_human
      when: midnight
      backupCount: 7
    syslog:
      class: logging.handlers.SysLogHandler
      formatter: basic_human
      address: /dev/log
    logstash:
      class: ores.logging.LogstashHandler
  formatters:
    basic_human:
      format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
    # Extra verbosity for untangling threads:
    threaded:
      format: "s%(asctime)s %(levelname)s %(name)s [P%(process)d T%(thread)d]: %(message)s"
