# Top level configuration
ores:
  scoring_system: celery_queue
  wsgi:
    application_root: ""
    url_prefix: ""
    scheme: 'https'
    error_host: 'https://www.wikimedia.org'
    error_alt: 'Wikimedia'
  data_paths:
    nltk: /srv/ores/config/submodules/wheels/nltk/
  home:
    footer: >
      Hosted by the <a href="//wikimediafoundation.org/">Wikimedia Foundation</a>
      &amp; written in <a href="//python.org">Python 3</a>.
# Score cache options
score_caches:
  ores_redis:
    class: ores.score_caches.Redis
    host: ores-redis-01
    port: 6380
    prefix: "ores"
    socket_timeout: 15

# Metrics collection options
metrics_collectors:
  local_logging:
    class: ores.metrics_collectors.Logger
  wmflabs_statsd:
    class: ores.metrics_collectors.Statsd
    host: labmon1001.eqiad.wmnet
    prefix: ores.{hostname}

# Score processor
scoring_systems:
  defaults:
    score_cache: ores_redis
    metrics_collector: wmflabs_statsd
    scoring_contexts:
      - arwiki
      - bnwiki
      - cawiki
      - cswiki
      - dewiki
      - enwiki
      - enwiktionary
      - elwiki
      - eswikibooks
      - eswiki
      - eswikiquote
      - etwiki
      - fawiki
      - fiwiki
      - frwiki
      - frwikisource
      - hewiki
      - hrwiki
      - huwiki
      - idwiki
      - iswiki
      - itwiki
      - kowiki
      - lvwiki
      - nlwiki
      - nowiki
      - plwiki
      - ptwiki
      - rowiki
      - ruwiki
      - simplewiki
      - sqwiki
      - svwiki
      - testwiki
      - tawiki
      - trwiki
      - ukwiki
      - viwiki
      - wikidatawiki
  local_single_thread:
    class: ores.scoring_systems.SingleThread
  local_process_pool:
    class: ores.scoring_systems.ProcessPool
    workers: 8
  celery_queue:
    class: ores.scoring_systems.CeleryQueue
    BROKER_URL: redis://ores-redis-01:6379
    BROKER_TRANSPORT_OPTIONS: {'socket_timeout': 15} # seconds
    CELERY_RESULT_BACKEND: redis://ores-redis-01:6379
    CELERY_ACCEPT_CONTENT: ['pickle']
    CELERY_TASK_SERIALIZER: 'pickle'
    CELERY_RESULT_SERIALIZER: 'pickle'
    CELERYD_CONCURRENCY: 24
    CELERYD_MAX_TASKS_PER_CHILD: 100
    timeout: 15 # seconds
    queue_maxsize: 100 # pending tasks
    CELERYD_HIJACK_ROOT_LOGGER: FALSE

# Scorers
scoring_contexts:
  arwiki:
    extractor: arwiki_api
    scorer_models:
      damaging: arwiki_damaging
      goodfaith: arwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  bnwiki:
    extractor: bnwiki_api
    scorer_models:
      reverted: bnwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  cawiki:
    extractor: cawiki_api
    scorer_models:
      damaging: cawiki_damaging
      goodfaith: cawiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  cswiki:
    extractor: cswiki_api
    scorer_models:
      damaging: cswiki_damaging
      goodfaith: cswiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  dewiki:
    extractor: dewiki_api
    scorer_models:
      reverted: dewiki_revert
    precache:
      reverted:
        "on": ["edit"]
  elwiki:
    extractor: elwiki_api
    scorer_models:
      reverted: elwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  enwiki:
    extractor: enwiki_api
    scorer_models:
      wp10: enwiki_wp10
      draftquality: enwiki_draftquality
      damaging: enwiki_damaging
      goodfaith: enwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  enwiktionary:
    extractor: enwiktionary_api
    scorer_models:
      reverted: enwiktionary_revert
    precache:
      reverted:
        "on": ["edit"]
  eswikibooks:
    extractor: eswikibooks_api
    scorer_models:
      damaging: eswikibooks_damaging
      goodfaith: eswikibooks_goodfaith
    precache:
      reverted:
        "on": ["edit"]
  eswiki:
    extractor: eswiki_api
    scorer_models:
      damaging: eswiki_damaging
      goodfaith: eswiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  eswikiquote:
    extractor: eswikiquote_api
    scorer_models:
      reverted: eswikiquote_revert
    precache:
      reverted:
        "on": ["edit"]
  etwiki:
    extractor: etwiki_api
    scorer_models:
      damaging: etwiki_damaging
      goodfaith: etwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  fawiki:
    extractor: fawiki_api
    scorer_models:
      damaging: fawiki_damaging
      goodfaith: fawiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  fiwiki:
    extractor: fiwiki_api
    scorer_models:
      damaging: fiwiki_damaging
      goodfaith: fiwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  frwiki:
    extractor: frwiki_api
    scorer_models:
      damaging: frwiki_damaging
      goodfaith: frwiki_goodfaith
      wp10: frwiki_wp10
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  frwikisource:
    extractor: frwikisource_api
    scorer_models:
      pagelevel: frwikisource_pagelevel
    precache:
      pagelevel:
        "on": ["edit"]
  hewiki:
    extractor: hewiki_api
    scorer_models:
      damaging: hewiki_damaging
      goodfaith: hewiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  hrwiki:
    extractor: hrwiki_api
    scorer_models:
      reverted: hrwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  huwiki:
    extractor: huwiki_api
    scorer_models:
      damaging: huwiki_damaging
      goodfaith: huwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  idwiki:
    extractor: idwiki_api
    scorer_models:
      reverted: idwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  iswiki:
    extractor: iswiki_api
    scorer_models:
      reverted: iswiki_revert
    precache:
      reverted:
        "on": ["edit"]
  itwiki:
    extractor: itwiki_api
    scorer_models:
      reverted: itwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  kowiki:
    extractor: kowiki_api
    scorer_models:
      reverted: kowiki_revert
    precache:
      reverted:
        "on": ["edit"]
  lvwiki:
    extractor: lvwiki_api
    scorer_models:
      damaging: lvwiki_damaging
      goodfaith: lvwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  nlwiki:
    extractor: nlwiki_api
    scorer_models:
      damaging: nlwiki_damaging
      goodfaith: nlwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  nowiki:
    extractor: nowiki_api
    scorer_models:
      reverted: nowiki_revert
    precache:
      reverted:
        "on": ["edit"]
  plwiki:
    extractor: plwiki_api
    scorer_models:
      goodfaith: plwiki_goodfaith
      damaging: plwiki_damaging
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  ptwiki:
    extractor: ptwiki_api
    scorer_models:
      damaging: ptwiki_damaging
      goodfaith: ptwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  rowiki:
    extractor: rowiki_api
    scorer_models:
      damaging: rowiki_damaging
      goodfaith: rowiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  ruwiki:
    extractor: ruwiki_api
    scorer_models:
      damaging: ruwiki_damaging
      goodfaith: ruwiki_goodfaith
      wp10: ruwiki_wp10
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  simplewiki:
    extractor: simplewiki_api
    scorer_models:
      wp10: enwiki_wp10
      draftquality: enwiki_draftquality
      damaging: enwiki_damaging
      goodfaith: enwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  sqwiki:
    extractor: sqwiki_api
    scorer_models:
      damaging: sqwiki_damaging
      goodfaith: sqwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  svwiki:
    extractor: svwiki_api
    scorer_models:
      damaging: svwiki_damaging
      goodfaith: svwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  tawiki:
    extractor: tawiki_api
    scorer_models:
      reverted: tawiki_revert
    precache:
      reverted:
        "on": ["edit"]
  testwiki:
    extractor: testwiki_offline
    scorer_models:
      reverted: testwiki_revert
      damaging: testwiki_revert
      goodfaith: testwiki_revert
    precache: {}
  trwiki:
    extractor: trwiki_api
    scorer_models:
      damaging: trwiki_damaging
      goodfaith: trwiki_goodfaith
      wp10: trwiki_wp10
    precache:
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  ukwiki:
    extractor: ukwiki_api
    scorer_models:
      reverted: ukwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  viwiki:
    extractor: viwiki_api
    scorer_models:
      reverted: viwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  wikidatawiki:
    extractor: wikidata_api
    scorer_models:
      damaging: wikidata_damaging
      goodfaith: wikidata_goodfaith
      itemquality: wikidata_itemquality
    precache:
      damaging:
        "on": ["nonbot_edit"]
      goodfaith:
        "on": ["nonbot_edit"]
      itemquality:
        "on": ["nonbot_edit"]

# Feature extractors
extractors:
  defaults:
    class: revscoring.extractors.api.Extractor
    user_agent: Object Revision Evaluation Service <ahalfaker@wikimedia.org>
    timeout: 5
  arwiki_api:
    host: https://ar.wikipedia.org
  bnwiki_api:
    host: https://bn.wikipedia.org
  cawiki_api:
    host: https://ca.wikipedia.org
  cswiki_api:
    host: https://cs.wikipedia.org
  dewiki_api:
    host: https://de.wikipedia.org
  elwiki_api:
    host: https://el.wikipedia.org
  enwiki_api:
    host: https://en.wikipedia.org
  enwiktionary_api:
    host: https://en.wiktionary.org
  eswiki_api:
    host: https://es.wikipedia.org
  eswikibooks_api:
    host: https://es.wikibooks.org
  eswikiquote_api:
    host: https://es.wikiquote.org
  etwiki_api:
    host: https://et.wikipedia.org
  fawiki_api:
    host: https://fa.wikipedia.org
  fiwiki_api:
    host: https://fi.wikipedia.org
  frwiki_api:
    host: https://fr.wikipedia.org
  frwikisource_api:
    host: https://fr.wikisource.org
  hewiki_api:
    host: https://he.wikipedia.org
  hrwiki_api:
    host: https://hr.wikipedia.org
  huwiki_api:
    host: https://hu.wikipedia.org
  idwiki_api:
    host: https://id.wikipedia.org
  iswiki_api:
    host: https://is.wikipedia.org
  itwiki_api:
    host: https://it.wikipedia.org
  kowiki_api:
    host: https://ko.wikipedia.org
  lvwiki_api:
    host: https://lv.wikipedia.org
  nlwiki_api:
    host: https://nl.wikipedia.org
  nowiki_api:
    host: https://no.wikipedia.org
  plwiki_api:
    host: https://pl.wikipedia.org
  ptwiki_api:
    host: https://pt.wikipedia.org
  rowiki_api:
    host: https://ro.wikipedia.org
  ruwiki_api:
    host: https://ru.wikipedia.org
  simplewiki_api:
    host: https://simple.wikipedia.org
  sqwiki_api:
    host: https://sq.wikipedia.org
  svwiki_api:
    host: https://sv.wikipedia.org
  testwiki_offline:
    class: revscoring.extractors.OfflineExtractor
  tawiki_api:
    host: https://tr.wikipedia.org
  trwiki_api:
    host: https://tr.wikipedia.org
  ukwiki_api:
    host: https://uk.wikipedia.org
  viwiki_api:
    host: https://vi.wikipedia.org
  wikidata_api:
    host: https://wikidata.org

# Scorer models
scorer_models:
  defaults:
    class: revscoring.Model
  arwiki_damaging:
    model_file: submodules/editquality/models/arwiki.damaging.gradient_boosting.model
  arwiki_goodfaith:
    model_file: submodules/editquality/models/arwiki.goodfaith.gradient_boosting.model
  bnwiki_revert:
    model_file: submodules/editquality/models/bnwiki.reverted.gradient_boosting.model
  cawiki_damaging:
    model_file: submodules/editquality/models/cawiki.damaging.gradient_boosting.model
  cawiki_goodfaith:
    model_file: submodules/editquality/models/cawiki.goodfaith.gradient_boosting.model
  cswiki_damaging:
    model_file: submodules/editquality/models/cswiki.damaging.gradient_boosting.model
  cswiki_goodfaith:
    model_file: submodules/editquality/models/cswiki.goodfaith.gradient_boosting.model
  dewiki_revert:
    model_file: submodules/editquality/models/dewiki.reverted.gradient_boosting.model
  elwiki_revert:
    model_file: submodules/editquality/models/elwiki.reverted.gradient_boosting.model
  enwiki_draftquality:
    model_file: submodules/draftquality/models/enwiki.draft_quality.gradient_boosting.model.bz2
  enwiki_wp10:
    model_file: submodules/wikiclass/models/enwiki.nettrom_wp10.gradient_boosting.model
  enwiki_damaging:
    model_file: submodules/editquality/models/enwiki.damaging.gradient_boosting.model
  enwiki_goodfaith:
    model_file: submodules/editquality/models/enwiki.goodfaith.gradient_boosting.model
  enwiktionary_revert:
    model_file: submodules/editquality/models/enwiktionary.reverted.rf.model
  eswiki_damaging:
    model_file: submodules/editquality/models/eswiki.damaging.gradient_boosting.model
  eswiki_goodfaith:
    model_file: submodules/editquality/models/eswiki.goodfaith.gradient_boosting.model
  eswikibooks_damaging:
    model_file: submodules/editquality/models/eswikibooks.damaging.gradient_boosting.model
  eswikibooks_goodfaith:
    model_file: submodules/editquality/models/eswikibooks.goodfaith.gradient_boosting.model
  eswikiquote_revert:
    model_file: submodules/editquality/models/eswikiquote.reverted.gradient_boosting.model
  etwiki_damaging:
    model_file: submodules/editquality/models/etwiki.damaging.gradient_boosting.model
  etwiki_goodfaith:
    model_file: submodules/editquality/models/etwiki.goodfaith.gradient_boosting.model
  fawiki_damaging:
    model_file: submodules/editquality/models/fawiki.damaging.gradient_boosting.model
  fawiki_goodfaith:
    model_file: submodules/editquality/models/fawiki.goodfaith.gradient_boosting.model
  fiwiki_damaging:
    model_file: submodules/editquality/models/fiwiki.damaging.gradient_boosting.model
  fiwiki_goodfaith:
    model_file: submodules/editquality/models/fiwiki.goodfaith.gradient_boosting.model
  frwiki_damaging:
    model_file: submodules/editquality/models/frwiki.damaging.gradient_boosting.model
  frwiki_goodfaith:
    model_file: submodules/editquality/models/frwiki.goodfaith.gradient_boosting.model
  frwiki_wp10:
    model_file: submodules/wikiclass/models/frwiki.wp10.gradient_boosting.model
  frwikisource_pagelevel:
    model_file: submodules/wikiclass/models/frwikisource.page_level.gradient_boosting.model
  hewiki_damaging:
    model_file: submodules/editquality/models/hewiki.damaging.rf.model
  hewiki_goodfaith:
    model_file: submodules/editquality/models/hewiki.goodfaith.gradient_boosting.model
  hrwiki_revert:
    model_file: submodules/editquality/models/hrwiki.reverted.gradient_boosting.model
  huwiki_damaging:
    model_file: submodules/editquality/models/huwiki.damaging.gradient_boosting.model
  huwiki_goodfaith:
    model_file: submodules/editquality/models/huwiki.goodfaith.gradient_boosting.model
  idwiki_revert:
    model_file: submodules/editquality/models/idwiki.reverted.gradient_boosting.model
  iswiki_revert:
    model_file: submodules/editquality/models/iswiki.reverted.gradient_boosting.model
  itwiki_revert:
    model_file: submodules/editquality/models/itwiki.reverted.gradient_boosting.model
  jawiki_revert:
    model_file: submodules/editquality/models/jawiki.reverted.gradient_boosting.model
  kowiki_revert:
    model_file: submodules/editquality/models/kowiki.reverted.gradient_boosting.model
  lvwiki_damaging:
    model_file: submodules/editquality/models/lvwiki.damaging.gradient_boosting.model
  lvwiki_goodfaith:
    model_file: submodules/editquality/models/lvwiki.goodfaith.gradient_boosting.model
  nlwiki_damaging:
    model_file: submodules/editquality/models/nlwiki.damaging.gradient_boosting.model
  nlwiki_goodfaith:
    model_file: submodules/editquality/models/nlwiki.goodfaith.gradient_boosting.model
  nowiki_revert:
    model_file: submodules/editquality/models/nowiki.reverted.gradient_boosting.model
  plwiki_damaging:
    model_file: submodules/editquality/models/plwiki.damaging.gradient_boosting.model
  plwiki_goodfaith:
    model_file: submodules/editquality/models/plwiki.goodfaith.rf.model
  ptwiki_damaging:
    model_file: submodules/editquality/models/ptwiki.damaging.gradient_boosting.model
  ptwiki_goodfaith:
    model_file: submodules/editquality/models/ptwiki.goodfaith.gradient_boosting.model
  rowiki_revert:
    model_file: submodules/editquality/models/rowiki.reverted.gradient_boosting.model
  rowiki_damaging:
    model_file: submodules/editquality/models/rowiki.damaging.gradient_boosting.model
  rowiki_goodfaith:
    model_file: submodules/editquality/models/rowiki.goodfaith.gradient_boosting.model
  ruwiki_damaging:
    model_file: submodules/editquality/models/ruwiki.damaging.gradient_boosting.model
  ruwiki_goodfaith:
    model_file: submodules/editquality/models/ruwiki.goodfaith.gradient_boosting.model
  ruwiki_wp10:
    model_file: submodules/wikiclass/models/ruwiki.wp10.gradient_boosting.model
  sqwiki_damaging:
    model_file: submodules/editquality/models/sqwiki.damaging.gradient_boosting.model
  sqwiki_goodfaith:
    model_file: submodules/editquality/models/sqwiki.goodfaith.gradient_boosting.model
  svwiki_damaging:
    model_file: submodules/editquality/models/svwiki.damaging.gradient_boosting.model
  svwiki_goodfaith:
    model_file: submodules/editquality/models/svwiki.goodfaith.gradient_boosting.model
  testwiki_revert:
    class: ores.scoring.models.RevIdScorer
    version: 0.0.3
  tawiki_revert:
    model_file: submodules/editquality/models/tawiki.reverted.gradient_boosting.model
  trwiki_damaging:
    model_file: submodules/editquality/models/trwiki.damaging.gradient_boosting.model
  trwiki_goodfaith:
    model_file: submodules/editquality/models/trwiki.goodfaith.gradient_boosting.model
  trwiki_wp10:
    model_file: submodules/wikiclass/models/trwiki.wp10.gradient_boosting.model
  ukwiki_revert:
    model_file: submodules/editquality/models/ukwiki.reverted.gradient_boosting.model
  viwiki_revert:
    model_file: submodules/editquality/models/viwiki.reverted.gradient_boosting.model
  wikidata_damaging:
    model_file: submodules/editquality/models/wikidatawiki.damaging.gradient_boosting.model
  wikidata_goodfaith:
    model_file: submodules/editquality/models/wikidatawiki.goodfaith.gradient_boosting.model
  wikidata_itemquality:
    model_file: submodules/wikiclass/models/wikidatawiki.item_quality.rf.model
