# Top level configuration
ores:
  score_processor: ores_celery
  wsgi:
    application_root: ""
    url_prefix: ""
  data_paths:
    nltk: /srv/ores/config/submodules/wheels/nltk/

# Score cache options
score_caches:
  ores_redis:
    class: ores.score_caches.Redis
    host: ores-redis-01
    port: 6380
    prefix: "ores"
    socket_timeout: 15

# Metrics collection options
metrics_collectors:
  local_logging:
    class: ores.metrics_collectors.Logger
  wmflabs_statsd:
    class: ores.metrics_collectors.Statsd
    host: labmon1001.eqiad.wmnet
    prefix: ores.{hostname}

# Score processor
score_processors:
  defaults:
    score_cache: ores_redis
    metrics_collector: wmflabs_statsd
    scoring_contexts:
      - arwiki
      - cswiki
      - dewiki
      - enwiki
      - enwiktionary
      - eswiki
      - etwiki
      - fawiki
      - frwiki
      - hewiki
      - huwiki
      - idwiki
      - itwiki
      - nlwiki
      - nowiki
      - plwiki
      - ptwiki
      - ruwiki
      - svwiki
      - testwiki
      - trwiki
      - ukwiki
      - viwiki
      - wikidatawiki
  ores_celery:
    class: ores.score_processors.Celery
    BROKER_URL: redis://ores-redis-01:6379
    BROKER_TRANSPORT_OPTIONS: {'socket_timeout': 15} # seconds
    CELERY_RESULT_BACKEND: redis://ores-redis-01:6379
    CELERY_ACCEPT_CONTENT: ['pickle']
    CELERY_TASK_SERIALIZER: 'pickle'
    CELERY_RESULT_SERIALIZER: 'pickle'
    CELERYD_CONCURRENCY: 16
    CELERYD_MAX_TASKS_PER_CHILD: 100
    timeout: 15 # seconds
    queue_maxsize: 100 # pending tasks


# Scorers
scoring_contexts:
  arwiki:
    extractor: arwiki_api
    scorer_models:
      reverted: arwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  cswiki:
    extractor: cswiki_api
    scorer_models:
      reverted: cswiki_revert
    precache:
      reverted:
        "on": ["edit"]
  dewiki:
    extractor: dewiki_api
    scorer_models:
      reverted: dewiki_revert
    precache:
      reverted:
        "on": ["edit"]
  enwiki:
    extractor: enwiki_api
    scorer_models:
      reverted: enwiki_revert
      wp10: enwiki_wp10
      damaging: enwiki_damaging
      goodfaith: enwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      reverted:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  enwiktionary:
    extractor: enwiktionary_api
    scorer_models:
      reverted: enwiktionary_revert
    precache:
      reverted:
        "on": ["edit"]
  eswiki:
    extractor: eswiki_api
    scorer_models:
      reverted: eswiki_revert
    precache:
      reverted:
        "on": ["edit"]
  etwiki:
    extractor: etwiki_api
    scorer_models:
      reverted: etwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  fawiki:
    extractor: fawiki_api
    scorer_models:
      reverted: fawiki_revert
      damaging: fawiki_damaging
      goodfaith: fawiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      reverted:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  frwiki:
    extractor: frwiki_api
    scorer_models:
      reverted: frwiki_revert
      wp10: frwiki_wp10
    precache:
      reverted:
        "on": ["edit"]
  hewiki:
    extractor: hewiki_api
    scorer_models:
      reverted: hewiki_revert
    precache:
      reverted:
        "on": ["edit"]
  huwiki:
    extractor: huwiki_api
    scorer_models:
      reverted: huwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  idwiki:
    extractor: idwiki_api
    scorer_models:
      reverted: idwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  itwiki:
    extractor: itwiki_api
    scorer_models:
      reverted: itwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  nlwiki:
    extractor: nlwiki_api
    scorer_models:
      reverted: nlwiki_revert
      damaging: nlwiki_damaging
      goodfaith: nlwiki_goodfaith
    precache:
      reverted:
        "on": ["edit"]
      damaging:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  nowiki:
    extractor: nowiki_api
    scorer_models:
      reverted: nowiki_revert
    precache:
      reverted:
        "on": ["edit"]
  plwiki:
    extractor: plwiki_api
    scorer_models:
      reverted: plwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  ptwiki:
    extractor: ptwiki_api
    scorer_models:
      reverted: ptwiki_revert
      damaging: ptwiki_damaging
      goodfaith: ptwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      reverted:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  testwiki:
    extractor: testwiki_offline
    scorer_models:
      reverted: testwiki_revert
      damaging: testwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  ruwiki:
    extractor: ruwiki_api
    scorer_models:
      reverted: ruwiki_revert
      damaging: ruwiki_damaging
      goodfaith: ruwiki_goodfaith
      wp10: ruwiki_wp10
    precache:
      damaging:
        "on": ["edit"]
      reverted:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  svwiki:
    extractor: svwiki_api
    scorer_models:
      reverted: svwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  trwiki:
    extractor: trwiki_api
    scorer_models:
      reverted: trwiki_revert
      damaging: trwiki_damaging
      goodfaith: trwiki_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      reverted:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]
  ukwiki:
    extractor: ukwiki_api
    scorer_models:
      reverted: ukwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  viwiki:
    extractor: viwiki_api
    scorer_models:
      reverted: viwiki_revert
    precache:
      reverted:
        "on": ["edit"]
  wikidatawiki:
    extractor: wikidata_api
    scorer_models:
      reverted: wikidata_revert
      damaging: wikidata_damaging
      goodfaith: wikidata_goodfaith
    precache:
      damaging:
        "on": ["edit"]
      reverted:
        "on": ["edit"]
      goodfaith:
        "on": ["edit"]

# Feature extractors
extractors:
  defaults:
    class: revscoring.extractors.api.Extractor
    user_agent: Object Revision Evaluation Service <ahalfaker@wikimedia.org>
    timeout: 5
  arwiki_api:
    host: https://ar.wikipedia.org
  cswiki_api:
    host: https://cs.wikipedia.org
  dewiki_api:
    host: https://de.wikipedia.org
  enwiki_api:
    host: https://en.wikipedia.org
  enwiktionary_api:
    host: https://en.wiktionary.org
  eswiki_api:
    host: https://es.wikipedia.org
  etwiki_api:
    host: https://et.wikipedia.org
  fawiki_api:
    host: https://fa.wikipedia.org
  frwiki_api:
    host: https://fr.wikipedia.org
  hewiki_api:
    host: https://he.wikipedia.org
  huwiki_api:
    host: https://hu.wikipedia.org
  idwiki_api:
    host: https://id.wikipedia.org
  itwiki_api:
    host: https://it.wikipedia.org
  nowiki_api:
    host: https://no.wikipedia.org
  nlwiki_api:
    host: https://nl.wikipedia.org
  plwiki_api:
    host: https://pl.wikipedia.org
  ptwiki_api:
    host: https://pt.wikipedia.org
  ruwiki_api:
    host: https://ru.wikipedia.org
  svwiki_api:
    host: https://sv.wikipedia.org
  testwiki_offline:
    class: revscoring.extractors.OfflineExtractor
  trwiki_api:
    host: https://tr.wikipedia.org
  ukwiki_api:
    host: https://uk.wikipedia.org
  viwiki_api:
    host: https://vi.wikipedia.org
  wikidata_api:
    host: https://wikidata.org

# Scorer models
scorer_models:
  defaults:
    class: revscoring.scorer_models.MLScorerModel
  arwiki_revert:
    model_file: submodules/editquality/models/arwiki.reverted.gradient_boosting.model
  cswiki_revert:
    model_file: submodules/editquality/models/cswiki.reverted.gradient_boosting.model
  dewiki_revert:
    model_file: submodules/editquality/models/dewiki.reverted.gradient_boosting.model
  enwiki_wp10:
    model_file: submodules/wikiclass/models/enwiki.nettrom_wp10.rf.model
  enwiki_revert:
    model_file: submodules/editquality/models/enwiki.reverted.gradient_boosting.model
  enwiki_damaging:
    model_file: submodules/editquality/models/enwiki.damaging.gradient_boosting.model
  enwiki_goodfaith:
    model_file: submodules/editquality/models/enwiki.goodfaith.gradient_boosting.model
  enwiktionary_revert:
    model_file: submodules/editquality/models/enwiktionary.reverted.rf.model
  eswiki_revert:
    model_file: submodules/editquality/models/eswiki.reverted.gradient_boosting.model
  etwiki_revert:
    model_file: submodules/editquality/models/etwiki.reverted.gradient_boosting.model
  fawiki_damaging:
    model_file: submodules/editquality/models/fawiki.damaging.gradient_boosting.model
  fawiki_goodfaith:
    model_file: submodules/editquality/models/fawiki.goodfaith.gradient_boosting.model
  fawiki_revert:
    model_file: submodules/editquality/models/fawiki.reverted.gradient_boosting.model
  frwiki_revert:
    model_file: submodules/editquality/models/frwiki.reverted.gradient_boosting.model
  frwiki_wp10:
    model_file: submodules/wikiclass/models/frwiki.wp10.rf.model
  hewiki_revert:
    model_file: submodules/editquality/models/hewiki.reverted.gradient_boosting.model
  huwiki_revert:
    model_file: submodules/editquality/models/huwiki.reverted.rf.model
  idwiki_revert:
    model_file: submodules/editquality/models/idwiki.reverted.gradient_boosting.model
  itwiki_revert:
    model_file: submodules/editquality/models/itwiki.reverted.gradient_boosting.model
  nlwiki_revert:
    model_file: submodules/editquality/models/nlwiki.reverted.gradient_boosting.model
  nlwiki_damaging:
    model_file: submodules/editquality/models/nlwiki.damaging.gradient_boosting.model
  nlwiki_goodfaith:
    model_file: submodules/editquality/models/nlwiki.goodfaith.gradient_boosting.model
  nowiki_revert:
    model_file: submodules/editquality/models/nowiki.reverted.gradient_boosting.model
  plwiki_damaging:
    model_file: submodules/editquality/models/plwiki.damaging.gradient_boosting.model
  plwiki_goodfaith:
    model_file: submodules/editquality/models/plwiki.goodfaith.rf.model
  plwiki_revert:
    model_file: submodules/editquality/models/plwiki.reverted.gradient_boosting.model
  ptwiki_damaging:
    model_file: submodules/editquality/models/ptwiki.damaging.gradient_boosting.model
  ptwiki_goodfaith:
    model_file: submodules/editquality/models/ptwiki.goodfaith.gradient_boosting.model
  ptwiki_revert:
    model_file: submodules/editquality/models/ptwiki.reverted.gradient_boosting.model
  ruwiki_damaging:
    model_file: submodules/editquality/models/ruwiki.damaging.gradient_boosting.model
  ruwiki_goodfaith:
    model_file: submodules/editquality/models/ruwiki.goodfaith.gradient_boosting.model
  ruwiki_revert:
    model_file: submodules/editquality/models/ruwiki.reverted.gradient_boosting.model
  ruwiki_wp10:
    model_file: submodules/wikiclass/models/ruwiki.wp10.rf.model
  svwiki_revert:
    model_file: submodules/editquality/models/svwiki.reverted.gradient_boosting.model
  testwiki_revert:
    class: ores.scorer_models.RevIdScorer
    version: 0.0.2
  trwiki_damaging:
    model_file: submodules/editquality/models/trwiki.damaging.gradient_boosting.model
  trwiki_goodfaith:
    model_file: submodules/editquality/models/trwiki.goodfaith.gradient_boosting.model
  trwiki_revert:
    model_file: submodules/editquality/models/trwiki.reverted.gradient_boosting.model
  ukwiki_revert:
    model_file: submodules/editquality/models/ukwiki.reverted.gradient_boosting.model
  viwiki_revert:
    model_file: submodules/editquality/models/viwiki.reverted.gradient_boosting.model
  wikidata_damaging:
    model_file: submodules/editquality/models/wikidatawiki.damaging.gradient_boosting.model
  wikidata_goodfaith:
    model_file: submodules/editquality/models/wikidatawiki.goodfaith.gradient_boosting.model
  wikidata_revert:
    model_file: submodules/editquality/models/wikidatawiki.reverted.gradient_boosting.model
